### ISSUE TITLE
Probably found a fix for you.

### ISSUE THREAD

**Issue by Hisamera** [kestrelm/Creature_UE4#27]
in Creature_UE4/CreatureEditorAndPlugin/CreaturePlugin/Source/CreaturePlugin/Private/
You have this
// Possible regression bug in UE4.24, the line below no longer compiles. However the definition for FSlateDataPayload::ResourceManager does exist in the Master branch
//FSlateShaderResourceProxy* ResourceProxy =  FSlateDataPayload::ResourceManager->GetShaderResource(*MyBrush);
FSlateResourceHandle Handle = FSlateApplication::Get().GetRenderer()->GetResourceHandle(*MyBrush);

Well, I'm a stuborn bastard and here you go
FSlateBrush * MyBrush = render_brush;
FSlateResourceHandle Handle = FSlateApplication::Get().GetRenderer()->GetResourceHandle(*MyBrush);
const FSlateShaderResourceProxy* ResourceProxy = Handle.GetResourceProxy();
Dunno if that does what you intended, but I;m getting no compiler errors now.

(Also this definition no longer exists in master, atleast it didn't when I looked XD)

**Comment by Hisamera** [comment]
Well that's interesting... it ate two asterisks in 
`*MyBrush and FSlateShaderResourceProxy*` Still getting new to that GitHub stuff.

**Comment by kestrelm** [comment]
Thanks, will take a look. 

On 13 January 2020 12:52:26 AM SGT, Dorian <notifications@github.com> wrote:
>in
>Creature_UE4/CreatureEditorAndPlugin/CreaturePlugin/Source/CreaturePlugin/Private/
>You have this
>// Possible regression bug in UE4.24, the line below no longer
>compiles. However the definition for FSlateDataPayload::ResourceManager
>does exist in the Master branch
>//FSlateShaderResourceProxy* ResourceProxy = 
>FSlateDataPayload::ResourceManager->GetShaderResource(*MyBrush);
>FSlateResourceHandle Handle =
>FSlateApplication::Get().GetRenderer()->GetResourceHandle(*MyBrush);
>
>Well, I'm a stuborn bastard and here you go
>FSlateBrush * MyBrush = render_brush;
>FSlateResourceHandle Handle =
>FSlateApplication::Get().GetRenderer()->GetResourceHandle(*MyBrush);
>const FSlateShaderResourceProxy* ResourceProxy =
>Handle.GetResourceProxy();
>Dunno if that does what you intended, but I;m getting no compiler
>errors now.
>
>(Also this definition no longer exists in master, atleast it didn't
>when I looked XD)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kestrelm/Creature_UE4/issues/27

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kestrelm** [comment]
Hello,
I just submitted an update/fix thanks to your hard work:
https://github.com/kestrelm/Creature_UE4/commit/b44e82e3f527c664f69d505947b7ced14fe8a9f0

Acknowledged you in the commit. 

Cheers
